apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: front-pipeline-deployment